In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

url = "https://raw.githubusercontent.com/mricardo89/data-mining/refs/heads/main/Unit-III/datasets/players_data-2025_2026.csv"
df = pd.read_csv(url)
print("Dataset cargado exitosamente desde GitHub")
print(f"Total de registros: {df.shape[0]} jugadores, {df.shape[1]} columnas.")
df.head()
#list(df.columns)

Dataset cargado exitosamente desde GitHub
Total de registros: 2839 jugadores, 102 columnas.

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,CrdY_stats_misc,CrdR_stats_misc,2CrdY,Fls,Fld,Off,Crs,Int,TklW,OG
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,eng Premier League,24.0,2000.0,37,30,...,3,0,0,20,51,5,37,17,27,0
1,2,Jerome Abbey,eng ENG,MF,Wolves,eng Premier League,15.0,2009.0,1,0,...,0,0,0,0,0,1,0,1,0,0
2,3,Zach Abbott,eng ENG,DF,Nottingham Forest,eng Premier League,19.0,2006.0,3,2,...,0,0,0,3,1,0,3,2,4,0
3,4,Jones El-Abdellaoui,ma MAR,"MF,FW",Celta Vigo,es La Liga,19.0,2006.0,22,4,...,0,0,0,7,3,2,30,3,3,0
4,5,Himad Abdelli,dz ALG,MF,Marseille,fr Ligue 1,25.0,1999.0,8,1,...,1,0,0,3,0,0,1,2,1,0

In [2]:
jugaGoat = "Erling Haaland"

features = ['Age', 'Gls', 'Ast', 'Min']

df_X = df[df['Player'] == jugaGoat].set_index('Player')[features]

df_X.columns = ['Edad', 'Goles', 'Asistencias', 'Minutos_J']

X_matriz = df_X.to_numpy()

print(f"Matriz de Scouting X para {jugaGoat}:")
display(df_X)

Matriz de Scouting X para Erling Haaland:

                Edad  Goles  Asistencias  Minutos_J
Player
Erling Haaland  25.0     27            8       2953